export interface ChapterOverview {
  title: string;
  summary: string;
  keyLessons: string[];
}

export const chapterOverviews: Record<string, Record<string, ChapterOverview>> = {
  "bhagavad-gītā": {
    "1": {
      title: "Observing the Armies on the Battlefield of Kurukṣetra",
      summary: "Arjuna faces his kinsmen on the battlefield and is overcome with grief, setting up the need for Kṛṣṇa's spiritual instruction.",
      keyLessons: ["The material body is temporary, but the soul is eternal", "Duty and duty alone should guide our actions"],
    },
    "2": {
      title: "Contents of the Gītā Summarized",
      summary: "Kṛṣṇa begins His teachings with the distinction between body and soul, karma-yoga, and the steady mind of a self-realized person.",
      keyLessons: ["The soul is eternal and never slain", "Work without attachment to the fruits"],
    },
    "3": {
      title: "Karma-yoga",
      summary: "Kṛṣṇa explains that action performed as a sacrifice for Viṣṇu is the path to freedom from bondage.",
      keyLessons: ["Perform prescribed duty for Kṛṣṇa's satisfaction", "Action in devotion is superior to renunciation of action"],
    },
    "4": {
      title: "Transcendental Knowledge",
      summary: "Kṛṣṇa reveals the nature of His descents, the importance of approaching a guru, and the knowledge that frees one from sin.",
      keyLessons: ["Kṛṣṇa appears to protect the righteous and reestablish dharma", "Approach a spiritual master in humility and service"],
    },
    "5": {
      title: "Karma-yoga — Action in Kṛṣṇa Consciousness",
      summary: "The perfection of karma-yoga is compared to the wisdom of the sāṅkhya philosophers and the path of selfless work.",
      keyLessons: ["One who works in devotion is in the renounced order of life", "Detachment from the fruits of work brings peace"],
    },
    "6": {
      title: "Dhyāna-yoga",
      summary: "Kṛṣṇa describes the process of meditating on the Supreme and the practice of controlling the mind for the yoga of devotion.",
      keyLessons: ["The mind must be controlled and focused on Kṛṣṇa", "A yogī is always in relationship with the Supreme"],
    },
    "7": {
      title: "Knowledge of the Absolute",
      summary: "Kṛṣṇa explains how He is the source of all, the material and spiritual energies, and how to approach Him through devotion.",
      keyLessons: ["Kṛṣṇa is the source of all material and spiritual worlds", "Surrender to Kṛṣṇa crosses beyond māyā"],
    },
    "8": {
      title: "Attaining the Supreme",
      summary: "Kṛṣṇa describes the process of remembering Him at the time of death and the universal forms of the Absolute.",
      keyLessons: ["Whatever one remembers at death determines the next body", "Fix the mind on the Supreme at all times"],
    },
    "9": {
      title: "The Most Confidential Knowledge",
      summary: "Kṛṣṇa declares the glories of pure devotional service and how He preserves what devotees have and supplies what they lack.",
      keyLessons: ["The most confidential knowledge is devotion to Kṛṣṇa", "Kṛṣṇa carries what the devotee lacks"],
    },
    "10": {
      title: "The Opulence of the Absolute",
      summary: "Kṛṣṇa describes His manifestations as the source of all beauty, strength, wisdom, and all wonderful things in the world.",
      keyLessons: ["The origin of all opulences is Kṛṣṇa", "The wise engage in Kṛṣṇa's devotional service"],
    },
    "11": {
      title: "The Universal Form",
      summary: "Arjuna prays to see Kṛṣṇa's universal form and is overwhelmed by the vision of the cosmic manifestation.",
      keyLessons: ["The universal form is the material manifestation of Kṛṣṇa", "Devotion is superior to the universal form"],
    },
    "12": {
      title: "Devotional Service",
      summary: "Kṛṣṇa explains the superiority of the path of devotion and the different stages of attachment to the Supreme.",
      keyLessons: ["Devotional service is the best path to the Supreme", "Even a small beginning in devotional service is never lost"],
    },
    "13": {
      title: "Nature, the Enjoyer and Consciousness",
      summary: "Kṛṣṇa describes the field of activities, the knower of the field, and the process of knowledge that leads to liberation.",
      keyLessons: ["Understand the difference between body, soul, and Supersoul", "Knowledge of the field and the knower is the path of liberation"],
    },
    "14": {
      title: "The Three Modes of Material Nature",
      summary: "The qualities of goodness, passion, and ignorance are described, along with their influence on the living entity.",
      keyLessons: ["Transcend the three modes of material nature", "Faith is determined by the mode one is in"],
    },
    "15": {
      title: "The Yoga of the Supreme Person",
      summary: "Kṛṣṇa compares the material world to a tree and explains the process of detachment and surrender to the Supreme Person.",
      keyLessons: ["Detach from the tree of material existence by surrender", "The Supreme Person is the source and maintenance of all"],
    },
    "16": {
      title: "The Divine and Demoniac Natures",
      summary: "The qualities of those born in divine nature and the qualities of the demoniac are contrasted.",
      keyLessons: ["Cultivate the divine qualities that lead to liberation", "Avoid the demoniac qualities that lead to bondage"],
    },
    "17": {
      title: "The Divisions of Faith",
      summary: "Kṛṣṇa explains how faith is determined by the three modes of nature and the different kinds of worship, food, austerity, and charity.",
      keyLessons: ["Faith is shaped by the modes of nature", "Worship, charity, and austerity should be done in goodness"],
    },
    "18": {
      title: "Conclusion — The Perfection of Renunciation",
      summary: "Kṛṣṇa summarizes the entire Gītā, explaining renunciation, the perfections of different service, and the highest duty of surrender.",
      keyLessons: ["Abandon all varieties of religion and surrender to Kṛṣṇa", "Kṛṣṇa will deliver the surrendered soul from all reactions"],
    },
  },

  "śrīmad-bhāgavatam": {
    "1": {
      title: "Questions by the Sages",
      summary: "Sages at Naimiṣāraṇya ask Sūta Gosvāmī about the highest duty and the glories of Śrīmad-Bhāgavatam.",
      keyLessons: ["The topmost occupation is devotional service", "Hearing the Bhāgavatam purifies the heart"],
    },
    "2": {
      title: "Divinity and Divine Service",
      summary: "Sūta explains the nature of the Supreme, the process of bhakti, and how it produces detachment and knowledge.",
      keyLessons: ["Bhakti immediately produces knowledge and detachment", "The Lord is the supreme enjoyer and the object of all sacrifice"],
    },
    "3": {
      title: "Kṛṣṇa Is the Source of All Incarnations",
      summary: "The incarnations of Kṛṣṇa are described, establishing that He is the original Personality of Godhead.",
      keyLessons: ["Kṛṣṇa is the source of all incarnations", "The Lord descends to protect the devotees and reestablish dharma"],
    },
    "4": {
      title: "The Appearance of Śrī Nārada",
      summary: "Nārada Muni tells the story of his birth from a maidservant and how he became a great devotee through association with devotees.",
      keyLessons: ["Association with pure devotees is the cause of spiritual advancement", "The mercy of the Lord can elevate anyone"],
    },
    "5": {
      title: "Nārada's Instructions on Śrīmad-Bhāgavatam for Vyāsadeva",
      summary: "Nārada instructs Vyāsadeva to complete the Bhāgavatam, explaining the perfection of devotional literature.",
      keyLessons: ["The Bhāgavatam is the spotless Purāṇa", "One should write and speak for the satisfaction of the Lord"],
    },
    "6": {
      title: "Conversation Between Nārada and Vyāsadeva",
      summary: "Vyāsadeva meditates and sees the Supreme, then composes the Bhāgavatam to relieve the conditioned souls.",
      keyLessons: ["The Supreme Lord can be seen by meditation and devotion", "The Bhāgavatam is the remedy for the conditioned soul"],
    },
    "7": {
      title: "The Son of Droṇa Punished",
      summary: "Aśvatthāmā is punished for killing the sons of the Pāṇḍavas, and Parīkṣit is saved in the womb.",
      keyLessons: ["The Lord protects His devotees", "Sinful actions are punished by the Lord's representatives"],
    },
    "8": {
      title: "Prayers by Queen Kuntī and Parīkṣit Saved",
      summary: "Queen Kuntī offers prayers to Kṛṣṇa, and Parīkṣit is saved from the brahmāstra.",
      keyLessons: ["Kuntī's prayers reveal the mood of a pure devotee", "The Lord protects those who depend on Him"],
    },
    "9": {
      title: "The Passing Away of Bhīṣmadeva",
      summary: "Bhīṣmadeva passes away while meditating on Kṛṣṇa, demonstrating the perfection of dying in Kṛṣṇa consciousness.",
      keyLessons: ["Fix the mind on Kṛṣṇa at the time of death", "A devotee is not afraid of death"],
    },
    "10": {
      title: "Departure of Lord Kṛṣṇa for Dvārakā",
      summary: "Kṛṣṇa leaves Hastināpura for Dvārakā, and the glories of His presence are described.",
      keyLessons: ["The Lord's presence is the greatest fortune", "Separation from the Lord is the cause of distress"],
    },
    "11": {
      title: "Lord Kṛṣṇa's Entrance into Dvārakā",
      summary: "Kṛṣṇa enters the city of Dvārakā and is worshiped by the citizens as the supreme beloved.",
      keyLessons: ["The citizens of Dvārakā enjoyed the Lord's association", "Association with the Lord is the highest pleasure"],
    },
    "12": {
      title: "Birth of Emperor Parīkṣit",
      summary: "Parīkṣit is born and the sages foretell his future greatness as a protector of the Bhāgavatam.",
      keyLessons: ["A great devotee is born to protect the Lord's glories", "The Lord appears in the dynasty of the devotees"],
    },
    "13": {
      title: "Dhṛtarāṣṭra Quits Home",
      summary: "Dhṛtarāṣṭra renounces his kingdom and family, assisted by Vidura, and the value of the last days of life is discussed.",
      keyLessons: ["Renunciation at the end of life is valuable", "The association of the holy is essential for spiritual progress"],
    },
    "14": {
      title: "The Disappearance of Lord Kṛṣṇa",
      summary: "The disappearance of Kṛṣṇa and the departure of the Pāṇḍavas from the world are described.",
      keyLessons: ["The Lord's disappearance is an apparent event for the conditioned soul", "The material world becomes empty without the Lord"],
    },
    "15": {
      title: "The Pāṇḍavas Retire Timely",
      summary: "The Pāṇḍavas retire and Mahārāja Parīkṣit begins to rule the world under the guidance of the Lord.",
      keyLessons: ["A wise person retires at the proper time", "The king should rule for the welfare of the citizens"],
    },
    "16": {
      title: "How Parīkṣit Received the Age of Kali",
      summary: "Parīkṣit travels the earth and prepares the way for the Kali-yuga, while protecting the principles of religion.",
      keyLessons: ["The king is responsible for checking the influence of Kali", "Religious principles must be protected by the rulers"],
    },
    "17": {
      title: "Punishment and Reward of Kali",
      summary: "Parīkṣit punishes the personified Kali and gives him places to reside in the Kali-yuga.",
      keyLessons: ["Kali is allowed to exist in certain places", "The king should not tolerate irreligious behavior"],
    },
    "18": {
      title: "Mahārāja Parīkṣit Cursed by a Brāhmaṇa Boy",
      summary: "Parīkṣit is cursed to die within seven days, and he accepts the curse as the Lord's mercy.",
      keyLessons: ["A devotee accepts all circumstances as Kṛṣṇa's mercy", "The opportunity to remember the Lord at death is the greatest gift"],
    },
    "19": {
      title: "The Appearance of Śukadeva Gosvāmī",
      summary: "Śukadeva Gosvāmī appears and is invited to recite the Bhāgavatam before Mahārāja Parīkṣit.",
      keyLessons: ["The Bhāgavatam is spoken by the self-realized soul", "Hearing the Bhāgavatam is the remedy for the fallen age"],
    },
  },

  "kṛṣṇa": {
    "1": { title: "The Advent of Lord Kṛṣṇa", summary: "The circumstances surrounding Kṛṣṇa's appearance in the prison of Kaṁsa are described.", keyLessons: ["The Lord appears by His own will", "The Lord's birth is transcendental"] },
    "2": { title: "Prayers by the Demigods for Lord Kṛṣṇa in the Womb", summary: "The demigods pray to the Lord in the womb of Devakī.", keyLessons: ["The demigods serve the Lord's mission", "The Lord's appearance is prayed for by all devotees"] },
    "3": { title: "The Birth of Lord Kṛṣṇa", summary: "Kṛṣṇa is born and the prison of Kaṁsa becomes filled with light.", keyLessons: ["The Lord's birth is accompanied by auspicious signs", "Devotees recognize the Lord's appearance"] },
    "4": { title: "Kaṁsa Begins His Persecutions", summary: "Kaṁsa attempts to kill the children of Devakī and Vasudeva.", keyLessons: ["The demoniac try to oppose the Lord's mission", "The Lord protects His devotees"] },
    "5": { title: "The Meeting of Nanda and Vasudeva", summary: "Vasudeva takes Kṛṣṇa to Gokula and exchanges Him with the daughter of Yaśodā.", keyLessons: ["The Lord's pastimes are arranged by transcendental exchange", "The parents of the Lord are great devotees"] },
    "6": { title: "Pūtanā Killed", summary: "The demoness Pūtanā tries to kill Kṛṣṇa but is liberated by His mercy.", keyLessons: ["Even enemies of the Lord can attain liberation", "The Lord's mercy is causeless"] },
    "7": { title: "The Salvation of Tṛṇāvarta", summary: "The whirlwind demon Tṛṇāvarta is killed by the child Kṛṣṇa.", keyLessons: ["The Lord's protection is absolute", "Demons are defeated by the Lord's childhood pastimes"] },
    "8": { title: "Vision of the Universal Form", summary: "Mother Yaśodā sees the universal form within Kṛṣṇa's mouth.", keyLessons: ["The Lord reveals His cosmic form to His mother", "The Lord's childhood pastimes are full of opulence"] },
    "9": { title: "Mother Yaśodā Binds Lord Kṛṣṇa", summary: "Yaśodā binds Kṛṣṇa to the grinding mortar, demonstrating the Lord's subordination to His devotees.", keyLessons: ["The Lord becomes bound by the love of His devotee", "Pure love is more powerful than the Lord's omnipotence"] },
    "10": { title: "The Deliverance of Nalakūvara and Maṇigrīva", summary: "Kṛṣṇa delivers the cursed sons of Kuvera and restores them to their positions.", keyLessons: ["The Lord's curse is also mercy", "Devotees are restored by the Lord's association"] },
    "11": { title: "Killing the Demons Vatsāsura and Bakāsura", summary: "Kṛṣṇa kills the demons who attack the cowherd boys in the form of animals.", keyLessons: ["The Lord protects the cowherd boys and calves", "Demons are destroyed by the Lord's mercy"] },
    "12": { title: "The Killing of the Aghāsura Demon", summary: "Kṛṣṇa kills the great serpent demon Aghāsura and saves the cowherd boys.", keyLessons: ["The Lord enters the demon's mouth and liberates him", "The Lord's friends are always protected"] },
    "13": { title: "The Stealing of the Boys and Calves by Brahmā", summary: "Lord Brahmā steals the boys and calves to test Kṛṣṇa's power.", keyLessons: ["The Lord expands Himself to fulfill every role", "Brahmā is bewildered by the Lord's māyā"] },
    "14": { title: "Prayers Offered by Lord Brahmā to Lord Kṛṣṇa", summary: "Brahmā offers prayers after realizing Kṛṣṇa's supreme position.", keyLessons: ["Brahmā acknowledges Kṛṣṇa as the Supreme Lord", "The Lord's lotus feet are the shelter of all"] },
    "15": { title: "The Killing of Dhenukāsura", summary: "Kṛṣṇa and Balarāma kill the ass demon Dhenukāsura in the tāla forest.", keyLessons: ["The Lord enjoys with the cowherd boys in the forest", "Demons are destroyed for the protection of the devotees"] },
    "16": { title: "Subduing Kāliya", summary: "Kṛṣṇa subdues the serpent Kāliya in the Yamunā river.", keyLessons: ["The Lord's dancing on Kāliya's hoods purifies the river", "Even the envious can be delivered by the Lord's mercy"] },
    "17": { title: "Extinguishing the Forest Fire", summary: "Kṛṣṇa swallows the forest fire to save the cowherd boys and cows.", keyLessons: ["The Lord's power is unlimited", "The Lord protects His devotees from all dangers"] },
    "18": { title: "Killing the Demon Pralambāsura", summary: "The demon Pralambāsura is killed by Balarāma while carrying Him.", keyLessons: ["Balarāma displays His strength as Kṛṣṇa's elder brother", "The cowherd boys' games are full of spiritual significance"] },
    "19": { title: "Devouring the Forest Fire", summary: "Kṛṣṇa devours another forest fire that threatens the residents of Vṛndāvana.", keyLessons: ["The Lord's devouring the fire is a display of mercy", "The residents of Vṛndāvana depend fully on Kṛṣṇa"] },
    "20": { title: "Description of Autumn", summary: "The autumn season in Vṛndāvana is described as Kṛṣṇa's flute attracts the gopīs.", keyLessons: ["The changing seasons in Vṛndāvana are filled with Kṛṣṇa's pleasure", "The gopīs are attracted by the sound of Kṛṣṇa's flute"] },
    "21": { title: "The Gopīs Attracted by the Flute", summary: "The gopīs leave their homes to follow the sound of Kṛṣṇa's flute.", keyLessons: ["The gopīs' love for Kṛṣṇa is spontaneous and pure", "The Lord's flute attracts the hearts of the devotees"] },
    "22": { title: "Stealing the Garments of the Unmarried Gopī Girls", summary: "Kṛṣṇa steals the garments of the gopīs and teaches them about surrender.", keyLessons: ["The gopīs surrender everything to Kṛṣṇa", "The Lord's pastimes are filled with spiritual exchange"] },
    "23": { title: "Delivering the Wives of the Brāhmaṇas", summary: "Kṛṣṇa delivers the wives of the brāhmaṇas who performed sacrifices and rewards their devotion.", keyLessons: ["The Lord accepts the simple offerings of the devoted wives", "Ritual without devotion does not satisfy the Lord"] },
    "24": { title: "Worshiping Govardhana Hill", summary: "Kṛṣṇa stops the Indra-yajña and establishes the worship of Govardhana Hill.", keyLessons: ["The Lord is the source of all sacrifices", "Worship should be offered to the Lord and His devotees"] },
    "25": { title: "Devastating Rainfall in Vṛndāvana", summary: "Indra sends a devastating rainstorm, and Kṛṣṇa lifts Govardhana Hill to protect the residents.", keyLessons: ["The Lord's little finger lifts the entire hill", "The residents of Vṛndāvana take shelter of Kṛṣṇa"] },
    "26": { title: "Wonderful Kṛṣṇa", summary: "The cowherd men describe the wonderful activities of Kṛṣṇa and express their love.", keyLessons: ["The residents of Vṛndāvana see Kṛṣṇa as their own son", "The Lord's pastimes are wonderful and inconceivable"] },
    "27": { title: "Prayers by Indra, the King of Heaven", summary: "Indra realizes his offense and offers prayers to Kṛṣṇa after being humbled.", keyLessons: ["Even the king of heaven is subordinate to Kṛṣṇa", "The Lord's mercy is the cause of all opulences"] },
    "28": { title: "Releasing Nanda Mahārāja from the Clutches of Varuṇa", summary: "Kṛṣṇa enters the kingdom of Varuṇa and rescues Nanda Mahārāja.", keyLessons: ["The Lord enters even the abodes of the demigods for His devotee", "The Lord's father is honored by all"] },
    "29": { title: "The Rāsa Dance: Introduction", summary: "Kṛṣṇa begins the rāsa dance with the gopīs under the autumn moon.", keyLessons: ["The rāsa dance is the highest expression of spiritual love", "The gopīs are the topmost devotees of the Lord"] },
    "30": { title: "Kṛṣṇa's Hiding from the Gopīs", summary: "Kṛṣṇa disappears during the rāsa dance to increase the gopīs' longing.", keyLessons: ["Separation increases the intensity of love", "The gopīs' love is unalloyed and exclusive"] },
    "31": { title: "Songs by the Gopīs", summary: "The gopīs sing about Kṛṣṇa's pastimes and Their search for Him.", keyLessons: ["The gopīs' songs are the highest poetry of devotion", "The Lord is the sole object of the gopīs' love"] },
    "32": { title: "Kṛṣṇa Returns to the Gopīs", summary: "Kṛṣṇa returns to the gopīs and continues the rāsa dance.", keyLessons: ["The Lord is conquered by the love of the gopīs", "The rāsa dance is the dance of divine love"] },
    "33": { title: "Description of the Rāsa Dance", summary: "The rāsa dance is described in detail, with Kṛṣṇa expanding Himself to dance with each gopī.", keyLessons: ["The Lord expands Himself for each devotee", "The rāsa dance is the summit of spiritual ecstasy"] },
    "34": { title: "Vidyādhara Liberated and the Demon Śaṅkhacūḍa Killed", summary: "Kṛṣṇa liberates a cursed vidyādhara and kills the demon Śaṅkhacūḍa.", keyLessons: ["The Lord's touch liberates the conditioned soul", "The Lord protects the gopīs from demons"] },
    "35": { title: "The Gopīs' Feelings of Separation", summary: "The gopīs experience separation from Kṛṣṇa after the rāsa dance.", keyLessons: ["Separation in love is a high stage of devotion", "The gopīs' love is the standard of selfless devotion"] },
    "36": { title: "Kaṁsa Sends Akrūra for Kṛṣṇa", summary: "Kaṁsa sends Akrūra to bring Kṛṣṇa and Balarāma to Mathurā.", keyLessons: ["The demoniac plan to kill the Lord, but their plans fail", "Akrūra is a devotee in the service of the Lord"] },
    "37": { title: "Killing the Keśī Demon and Vyomāsura", summary: "Kṛṣṇa kills the horse demon Keśī and the demon Vyomāsura.", keyLessons: ["The Lord's strength is unmatched", "The Lord protects the cowherd community"] },
    "38": { title: "Akrūra's Arrival in Vṛndāvana", summary: "Akrūra arrives in Vṛndāvana and is overwhelmed by the spiritual atmosphere.", keyLessons: ["The dust of Vṛndāvana is purifying", "A pure devotee weeps in ecstasy upon seeing the Lord's abode"] },
    "39": { title: "Akrūra's Return Journey and His Vision of Viṣṇuloka", summary: "Akrūra sees the universal form in the Yamunā river during his return journey.", keyLessons: ["The Lord reveals His universal form to Akrūra", "The Yamunā river is the Lord's spiritual expansion"] },
    "40": { title: "Prayers by Akrūra", summary: "Akrūra offers prayers to the Supreme Lord and the devotees of Vṛndāvana.", keyLessons: ["Akrūra prays for the dust of the devotees' feet", "The Lord's devotees are more dear than the Lord Himself"] },
    "41": { title: "Kṛṣṇa Enters Mathurā", summary: "Kṛṣṇa and Balarāma enter Mathurā and are greeted by the residents.", keyLessons: ["The Lord's arrival in Mathurā is celebrated", "The devotees long for the Lord's association"] },
    "42": { title: "The Breaking of the Bow in the Sacrificial Arena", summary: "Kṛṣṇa breaks the bow of Kaṁsa in the sacrificial arena.", keyLessons: ["The Lord's strength shatters the demoniac pride", "The Lord's pastimes are full of divine power"] },
    "43": { title: "The Killing of the Elephant Kuvalayāpīḍa", summary: "Kṛṣṇa kills the elephant Kuvalayāpīḍa released by Kaṁsa.", keyLessons: ["The Lord defeats the powerful elephant demon", "The Lord's pastimes are sport for Him"] },
    "44": { title: "The Killing of Kaṁsa", summary: "Kṛṣṇa kills Kaṁsa and reinstates Ugrasena as king.", keyLessons: ["The Lord destroys the greatest demon", "The Lord establishes the rightful king"] },
    "45": { title: "Kṛṣṇa Recovers the Son of His Teacher", summary: "Kṛṣṇa recovers the son of His teacher Sāndīpani Muni from the ocean of death.", keyLessons: ["The Lord is grateful to His teacher", "The Lord's power extends even over death"] },
    "46": { title: "Uddhava Visits Vṛndāvana", summary: "Uddhava is sent by Kṛṣṇa to console the gopīs in Vṛndāvana.", keyLessons: ["The gopīs' love is the highest form of devotion", "Uddhava learns the superiority of the gopīs' love"] },
    "47": { title: "Delivery of the Message of Kṛṣṇa to the Gopīs", summary: "Uddhava delivers Kṛṣṇa's message to the gopīs, and they respond with deep love.", keyLessons: ["The gopīs' response to separation is full of wisdom", "The Lord's message increases the devotees' love"] },
    "48": { title: "Kṛṣṇa Pleases His Devotees", summary: "Kṛṣṇa sends various gifts to the gopīs and the residents of Vṛndāvana.", keyLessons: ["The Lord never forgets His devotees", "The gopīs are consoled by the Lord's remembrance"] },
    "49": { title: "Ill-motivated Dhṛtarāṣṭra", summary: "Kṛṣṇa and Balarāma visit the Pāṇḍavas and are received by Dhṛtarāṣṭra with ill motives.", keyLessons: ["The Lord is aware of the demoniac motives", "The Pāṇḍavas are protected by the Lord"] },
    "50": { title: "Kṛṣṇa Erects the Dvārakā Fort", summary: "Kṛṣṇa requests the construction of the city of Dvārakā to protect the Yadu dynasty.", keyLessons: ["The Lord arranges protection for His devotees", "Dvārakā is a manifestation of the Lord's opulence"] },
    "51": { title: "The Deliverance of Mucukunda", summary: "Kṛṣṇa delivers the sleeping king Mucukunda and kills the demon Kālayavana.", keyLessons: ["The Lord protects the righteous and destroys the wicked", "The Lord's glance is the cause of liberation"] },
    "52": { title: "Kṛṣṇa, the Raṇacora", summary: "Kṛṣṇa fights with the king of Magadha and displays His prowess.", keyLessons: ["The Lord's military strength is matchless", "The Lord protects His devotees from enemies"] },
    "53": { title: "Kṛṣṇa Kidnaps Rukmiṇī", summary: "Kṛṣṇa kidnaps Rukmiṇī and defeats her brother Rukmī.", keyLessons: ["The Lord fulfills the desires of His devotees", "Rukmiṇī's love for Kṛṣṇa is pure and selfless"] },
    "54": { title: "Kṛṣṇa Defeats All the Princes and Takes Rukmiṇī Home to Dvārakā", summary: "Kṛṣṇa defeats the princes and marries Rukmiṇī in Dvārakā.", keyLessons: ["The Lord is the supreme hero", "The marriage of Rukmiṇī and Kṛṣṇa is the perfection of conjugal love"] },
    "55": { title: "Pradyumna Born to Kṛṣṇa and Rukmiṇī", summary: "The birth of Pradyumna and the activities of the demon Śambara are described.", keyLessons: ["The Lord's family is part of His pastimes", "The Lord's son is protected by His mercy"] },
    "56": { title: "The Story of the Syamantaka Jewel", summary: "The story of the Syamantaka jewel and Kṛṣṇa's marriage to Satyabhāmā and Jāmbavatī.", keyLessons: ["The Lord is the rightful owner of all jewels", "The Lord's pastimes are full of royal opulence"] },
    "57": { title: "The Killing of Satrājit and Śatadhanvā", summary: "Kṛṣṇa punishes Satrājit and Śatadhanvā for their offenses.", keyLessons: ["The Lord is the supreme judge", "The Lord protects the reputation of His devotees"] },
    "58": { title: "Five Queens Married by Kṛṣṇa", summary: "Kṛṣṇa marries five queens and expands His royal household.", keyLessons: ["The Lord's opulences are unlimited", "The queens of Dvārakā are great devotees"] },
    "59": { title: "The Deliverance of the Demon Bhaumāsura", summary: "Kṛṣṇa kills Bhaumāsura and rescues the princesses.", keyLessons: ["The Lord rescues the helpless", "The Lord's strength is the shelter of all"] },
    "60": { title: "Talks Between Kṛṣṇa and Rukmiṇī", summary: "Kṛṣṇa and Rukmiṇī discuss the nature of devotional love.", keyLessons: ["The Lord reciprocates with the love of His devotees", "Conjugal love in devotion is the highest mellow"] },
    "61": { title: "The Genealogy of the Family of Kṛṣṇa", summary: "The descendants of Kṛṣṇa and the Yadu dynasty are described.", keyLessons: ["The Lord's family extends throughout the world", "The Yadu dynasty is filled with the Lord's devotees"] },
    "62": { title: "The Meeting of Ūṣā and Aniruddha", summary: "The romantic meeting of Ūṣā and Aniruddha is described.", keyLessons: ["The Lord's family members display transcendental love", "The Lord's pastimes are full of divine relationships"] },
    "63": { title: "Lord Kṛṣṇa Fights with Bāṇāsura", summary: "Kṛṣṇa fights with Bāṇāsura and cuts off his arms.", keyLessons: ["The Lord's valor is unmatched", "The Lord is the protector of the demigods"] },
    "64": { title: "The Story of King Nṛga", summary: "The story of King Nṛga and the power of charity is described.", keyLessons: ["Charity to the wrong recipient can be counterproductive", "The Lord releases the soul from the results of mistakes"] },
    "65": { title: "Lord Balarāma Visits Vṛndāvana", summary: "Balarāma visits Vṛndāvana and enjoys with the cowherd boys and gopīs.", keyLessons: ["Balarāma is the original spiritual master", "The Lord's brother is as dear as the Lord Himself"] },
    "66": { title: "The Deliverance of Pauṇḍraka and the King of Kāśī", summary: "Kṛṣṇa kills the false Vāsudeva Pauṇḍraka and the king of Kāśī.", keyLessons: ["Impersonating the Lord leads to destruction", "The Lord destroys the false pride of demons"] },
    "67": { title: "The Deliverance of Dvivida Gorilla", summary: "Balarāma kills the gorilla Dvivida.", keyLessons: ["Balarāma's strength is the Lord's own", "The Lord's devotees are protected by the Lord's plenary portions"] },
    "68": { title: "The Marriage of Sāmba", summary: "Sāmba's marriage and the subsequent curse of the sages are described.", keyLessons: ["The Yadu dynasty is affected by the curse of the sages", "The Lord's pastimes include the end of His dynasty"] },
    "69": { title: "The Great Sage Nārada Visits the Different Homes of Lord Kṛṣṇa", summary: "Nārada visits Kṛṣṇa's palaces and is amazed by His expansions.", keyLessons: ["The Lord expands Himself to be with each queen", "The Lord's opulence is inconceivable"] },
    "70": { title: "Lord Kṛṣṇa's Daily Activities", summary: "The daily schedule of Kṛṣṇa in Dvārakā is described.", keyLessons: ["The Lord's daily activities are full of spiritual significance", "The Lord's life is the model for all devotees"] },
    "71": { title: "Lord Kṛṣṇa in Indraprastha City", summary: "Kṛṣṇa visits the Pāṇḍavas in Indraprastha and is honored.", keyLessons: ["The Lord is honored by the Pāṇḍavas", "The Lord's presence makes any place glorious"] },
    "72": { title: "The Liberation of King Jarāsandha", summary: "Kṛṣṇa arranges the liberation of King Jarāsandha through Bhīma.", keyLessons: ["The Lord's devotee can conquer the unconquerable", "The Lord's mercy is available even to enemies"] },
    "73": { title: "Lord Kṛṣṇa Returns to the City of Hastināpura", summary: "Kṛṣṇa returns to Hastināpura and mediates between the Pāṇḍavas and Kauravas.", keyLessons: ["The Lord's peace mission is an example of diplomacy", "The Lord's devotees are protected by His counsel"] },
    "74": { title: "The Deliverance of Śiśupāla", summary: "Kṛṣṇa kills Śiśupāla at the Rājasūya sacrifice.", keyLessons: ["The Lord's enemies are liberated by His glance", "The Rājasūya sacrifice is completed by the Lord's presence"] },
    "75": { title: "Why Duryodhana Felt Insulted at the End of the Rājasūya Sacrifice", summary: "Duryodhana's envy is aroused by the Rājasūya sacrifice and Kṛṣṇa's honor.", keyLessons: ["Envy is the cause of the demoniac downfall", "The Lord's honor is the honor of the whole universe"] },
    "76": { title: "The Battle Between Śālva and Members of the Yadu Dynasty", summary: "The demon Śālva attacks Dvārakā and is defeated.", keyLessons: ["The Lord's city is protected by His potency", "The demons are destroyed by the Lord's associates"] },
    "77": { title: "The Deliverance of Śālva", summary: "Kṛṣṇa kills Śālva and his airship Saubha.", keyLessons: ["The Lord's weapons are divine and invincible", "No material power can defeat the Lord"] },
    "78": { title: "The Killing of Dantavakra, Vidūratha and Romaharṣaṇa", summary: "Kṛṣṇa kills the demons Dantavakra, Vidūratha, and Romaharṣaṇa.", keyLessons: ["The Lord destroys all enemies of the devotees", "The Lord's anger is transcendental and just"] },
    "79": { title: "The Liberation of Balvala, and Lord Balarāma's Touring the Sacred Places", summary: "Balarāma tours the sacred places and kills the demon Balvala.", keyLessons: ["Balarāma's travels sanctify the holy places", "The Lord's plenary portion is the original guru"] },
    "80": { title: "The Meeting of Lord Kṛṣṇa with Sudāmā Brāhmaṇa", summary: "Kṛṣṇa meets His childhood friend Sudāmā and blesses him.", keyLessons: ["The Lord's friendship is eternal", "The Lord blesses His devotee with spiritual wealth"] },
    "81": { title: "The Brāhmaṇa Sudāmā Blessed by Lord Kṛṣṇa", summary: "Sudāmā returns home and is blessed by the Lord with opulence and devotion.", keyLessons: ["The Lord's mercy is the highest wealth", "A pure devotee uses the Lord's gifts in His service"] },
    "82": { title: "Lord Kṛṣṇa and Balarāma Meet the Inhabitants of Vṛndāvana", summary: "Kṛṣṇa and Balarāma meet the residents of Vṛndāvana at Kurukṣetra.", keyLessons: ["The residents of Vṛndāvana long for Kṛṣṇa's return", "The Lord's separation increases the devotees' love"] },
    "83": { title: "Draupadī Meets the Queens of Kṛṣṇa", summary: "Draupadī meets the queens of Kṛṣṇa and hears about the Lord's glories.", keyLessons: ["The Lord's devotees glorify His pastimes", "The queens of Kṛṣṇa are the greatest devotees"] },
    "84": { title: "Sacrificial Ceremonies Performed by Vasudeva", summary: "Vasudeva performs sacrifices and Kṛṣṇa instructs him.", keyLessons: ["The Lord's father follows the Vedic principles", "The Lord's instructions are the highest guidance"] },
    "85": { title: "Spiritual Instruction for Vasudeva, and the Return of the Six Dead Sons of Devakī by Lord Kṛṣṇa", summary: "Kṛṣṇa instructs Vasudeva and brings back his six sons.", keyLessons: ["The Lord's instructions are the perfection of knowledge", "The Lord's mercy extends beyond this life"] },
    "86": { title: "The Kidnapping of Subhadrā, and Lord Kṛṣṇa's Visiting Śrutadeva and Bahulāśva", summary: "Kṛṣṇa arranges the marriage of Subhadrā and Arjuna and visits great devotees.", keyLessons: ["The Lord's family relationships are transcendental", "The Lord visits His devotees and honors them"] },
    "87": { title: "Prayers by the Personified Vedas", summary: "The personified Vedas offer prayers to Kṛṣṇa.", keyLessons: ["The Vedas glorify the Supreme Lord", "The Lord is the source of all Vedic knowledge"] },
    "88": { title: "The Deliverance of Lord Śiva", summary: "Kṛṣṇa delivers Lord Śiva from the demon Vṛkāsura.", keyLessons: ["Even the great demigods take shelter of Kṛṣṇa", "The Lord protects all devotees, including the demigods"] },
    "89": { title: "The Superexcellent Power of Kṛṣṇa", summary: "The superexcellent power of Kṛṣṇa is described through His pastimes.", keyLessons: ["The Lord's power is beyond material conception", "The Lord's pastimes are the source of all wonder"] },
    "90": { title: "Summary Description of Lord Kṛṣṇa's Pastimes", summary: "A summary of Kṛṣṇa's pastimes is given.", keyLessons: ["The Lord's pastimes are unlimited", "Hearing the Lord's pastimes liberates the conditioned soul"] },
  },

  "nectar of devotion": {
    "1": { title: "Characteristics of Pure Devotional Service", summary: "The definition and characteristics of pure, unalloyed devotional service are described.", keyLessons: ["Pure devotion is unmotivated and uninterrupted", "Bhakti is the only means to satisfy the self"] },
    "2": { title: "The First Stages of Devotion", summary: "The initial stages of devotional practice and the awakening of attachment to Kṛṣṇa are discussed.", keyLessons: ["Faith is the beginning of devotion", "Association with devotees nourishes bhakti"] },
    "3": { title: "Eligibility of the Candidate for Accepting Devotional Service", summary: "The eligibility and qualifications required for taking up devotional service are explained.", keyLessons: ["Anyone can become eligible by faith and association", "Humility and sincerity are essential"] },
    "4": { title: "Devotional Service Surpasses All Liberation", summary: "The superiority of devotional service over liberation and other spiritual achievements is shown.", keyLessons: ["Bhakti is superior to liberation", "The devotee does not desire anything but service"] },
    "5": { title: "The Purity of Devotional Service", summary: "The purity of devotional service and how it removes material contamination is described.", keyLessons: ["Devotion purifies the heart", "The devotee is freed from the reactions of karma"] },
    "6": { title: "How to Discharge Devotional Service", summary: "Practical methods of executing devotional service and the regulative principles are given.", keyLessons: ["Follow the regulative principles of devotion", "Hearing and chanting are the main practices"] },
    "7": { title: "Evidence Regarding Devotional Principles", summary: "Scriptural evidence is given to support the principles of devotional service.", keyLessons: ["The śāstras confirm the path of bhakti", "The authority of the guru is essential"] },
    "8": { title: "Offenses to Be Avoided", summary: "The ten offenses to be avoided while chanting the holy name and serving the Lord are described.", keyLessons: ["Avoid offenses to the holy name", "Respect the devotees and the spiritual master"] },
    "9": { title: "Further Consideration of Devotional Principles", summary: "Further elaboration on the principles of devotion and their application.", keyLessons: ["Understand the finer points of devotional practice", "Steadiness in practice is required"] },
    "10": { title: "Techniques of Hearing and Remembering", summary: "Techniques for hearing about Kṛṣṇa and remembering Him are explained.", keyLessons: ["Hearing is the beginning of devotional life", "Remembering Kṛṣṇa fixes the mind"] },
    "11": { title: "Aspects of Transcendental Service", summary: "Different aspects of devotional service and how they manifest are described.", keyLessons: ["Devotion has many aspects, all centered on Kṛṣṇa", "Every action can be offered in devotion"] },
    "12": { title: "Further Aspects of Transcendental Service", summary: "Further aspects of service and the development of rasa are discussed.", keyLessons: ["Devotional service matures into rasa", "Attachment to Kṛṣṇa grows by practice"] },
    "13": { title: "Five Potent Forms of Devotional Service", summary: "The five potent forms of devotional service and their effectiveness are described.", keyLessons: ["Hearing, chanting, remembering, serving, and worshiping are potent", "Each form of service has its unique power"] },
    "14": { title: "Devotional Qualifications", summary: "The qualifications that favor the development of devotional service are discussed.", keyLessons: ["Develop the qualities favorable to devotion", "Avoid the qualities that obstruct bhakti"] },
    "15": { title: "Spontaneous Devotional Service", summary: "The stage of spontaneous devotion and the awakening of spontaneous love are described.", keyLessons: ["Spontaneous devotion arises from attachment", "Rāgānugā bhakti follows the moods of the residents of Vṛndāvana"] },
    "16": { title: "Spontaneous Devotion Further Described", summary: "Further explanation of spontaneous devotion and its symptoms.", keyLessons: ["Spontaneous love is the highest stage of devotion", "The devotee acts out of intense love for Kṛṣṇa"] },
    "17": { title: "Ecstatic Love", summary: "The nature of ecstatic love for Kṛṣṇa and its symptoms are described.", keyLessons: ["Ecstatic love is the mature fruit of devotion", "The symptoms of love reveal the devotee's heart"] },
    "18": { title: "Character of One in Ecstatic Love", summary: "The character and behavior of a person absorbed in ecstatic love for Kṛṣṇa are discussed.", keyLessons: ["The devotee in ecstatic love is fully absorbed in Kṛṣṇa", "External consciousness is overcome by love"] },
    "19": { title: "Devotional Service in Pure Love of God", summary: "The perfection of devotional service in pure love of God is described.", keyLessons: ["Pure love of God is the highest perfection", "The devotee desires only Kṛṣṇa's happiness"] },
    "20": { title: "Transcendental Mellow", summary: "The transcendental mellows and the five primary relationships with Kṛṣṇa are introduced.", keyLessons: ["The five rasas are the mellows of devotion", "Each rasa has its unique flavor of love"] },
    "21": { title: "Qualities of Śrī Kṛṣṇa", summary: "The qualities of Kṛṣṇa and how they attract the devotees are described.", keyLessons: ["Kṛṣṇa's qualities are the basis of attraction", "The devotees are attracted by Kṛṣṇa's sweetness"] },
    "22": { title: "Qualities of Kṛṣṇa Further Explained", summary: "Further explanation of Kṛṣṇa's transcendental qualities and opulences.", keyLessons: ["Kṛṣṇa's qualities are unlimited", "The devotee meditates on the Lord's qualities"] },
    "23": { title: "Kṛṣṇa's Personality", summary: "The personality of Kṛṣṇa and His form as the supreme object of worship are discussed.", keyLessons: ["Kṛṣṇa is the supreme person", "His form is the object of the devotees' meditation"] },
    "24": { title: "Further Traits of Śrī Kṛṣṇa", summary: "Further traits and characteristics of Kṛṣṇa are described.", keyLessons: ["Kṛṣṇa's traits are the source of all attraction", "The devotee becomes absorbed in the Lord's traits"] },
    "25": { title: "Devotees of Kṛṣṇa", summary: "The various devotees of Kṛṣṇa and their relationships with Him are described.", keyLessons: ["The devotees relish different relationships with Kṛṣṇa", "Each devotee is dear to the Lord"] },
    "26": { title: "Stimulation for Ecstatic Love", summary: "The causes that stimulate ecstatic love for Kṛṣṇa are explained.", keyLessons: ["Association and remembrance stimulate love", "The devotee's heart is awakened by Kṛṣṇa's qualities"] },
    "27": { title: "Symptoms of Ecstatic Love", summary: "The symptoms that manifest when a devotee is absorbed in ecstatic love.", keyLessons: ["Ecstatic symptoms reveal the devotee's internal state", "Love of Kṛṣṇa transforms the body and mind"] },
    "28": { title: "Existential Ecstatic Love", summary: "The existential nature of ecstatic love and how it becomes the devotee's very life.", keyLessons: ["Ecstatic love is the living condition of the advanced devotee", "The devotee cannot live without Kṛṣṇa"] },
    "29": { title: "Expressions of Love for Kṛṣṇa", summary: "The various expressions of love for Kṛṣṇa and their beauty are described.", keyLessons: ["Love for Kṛṣṇa is expressed in many ways", "The devotee's expressions are pleasing to the Lord"] },
    "30": { title: "Further Features of Ecstatic Love for Kṛṣṇa", summary: "Further features of ecstatic love and the advanced stages of devotion.", keyLessons: ["Ecstatic love has many features", "The advanced devotee experiences the Lord's presence constantly"] },
    "31": { title: "Additional Symptoms", summary: "Additional symptoms of ecstatic love and their significance.", keyLessons: ["The symptoms of love are varied and wonderful", "The Lord reciprocates with the devotee's love"] },
    "32": { title: "Symptoms of Continuous Ecstasy", summary: "The symptoms of continuous ecstasy and the devotee's unbroken absorption in Kṛṣṇa.", keyLessons: ["Continuous ecstasy is the highest stage", "The devotee sees Kṛṣṇa everywhere"] },
    "33": { title: "Indirect Expressions of Ecstatic Love", summary: "The indirect and subtle expressions of ecstatic love are described.", keyLessons: ["Love can be expressed indirectly", "The devotee's heart is fully revealed to Kṛṣṇa"] },
    "34": { title: "The Nectar of Devotion", summary: "The nectar of devotion and the culmination of all bhakti-rasa are described.", keyLessons: ["The nectar of devotion is the highest taste", "Bhakti-rasa is the perfection of life"] },
    "35": { title: "Neutral Love of God", summary: "The neutral relationship with Kṛṣṇa and the worship of the Lord as the supreme object.", keyLessons: ["Neutral love is the beginning of rasa", "The Lord is worshiped as the supreme controller"] },
    "36": { title: "Transcendental Affection (Servitude)", summary: "The servitude relationship with Kṛṣṇa and the mood of dasya-rasa.", keyLessons: ["Servitude is the foundational relationship with Kṛṣṇa", "The servant of the Lord is the most fortunate"] },
    "37": { title: "Impetuses for Kṛṣṇa's Service", summary: "The impetuses that awaken the desire to serve Kṛṣṇa in various relationships.", keyLessons: ["Impetuses awaken the devotee's service attitude", "The devotee responds to Kṛṣṇa's beauty and qualities"] },
    "38": { title: "Indifference and Separation", summary: "The experiences of indifference and separation in the advanced stages of devotion.", keyLessons: ["Separation intensifies the devotee's love", "The Lord is the remedy for separation"] },
    "39": { title: "Ways of Meeting Kṛṣṇa", summary: "The ways in which the devotee meets Kṛṣṇa and the ecstasy of union.", keyLessons: ["Meeting Kṛṣṇa is the highest fulfillment", "The devotee's meeting is full of transcendental emotions"] },
    "40": { title: "Reverential Devotion of Sons and Other Subordinates", summary: "The reverential devotion of sons and subordinates to Kṛṣṇa is described.", keyLessons: ["Reverential devotion is full of respect and awe", "The devotee serves as a subordinate of the Lord"] },
    "41": { title: "Fraternal Devotion", summary: "The fraternal relationship with Kṛṣṇa and the mood of sakhya-rasa are discussed.", keyLessons: ["Friendship with Kṛṣṇa is the highest equality", "The cowherd boys enjoy the Lord's company"] },
    "42": { title: "Fraternal Loving Affairs", summary: "The loving affairs of friendship with Kṛṣṇa are further elaborated.", keyLessons: ["Friendship with Kṛṣṇa is full of intimacy", "The devotee treats the Lord as a friend"] },
    "43": { title: "Parenthood", summary: "The parental relationship with Kṛṣṇa and the mood of vātsalya-rasa are described.", keyLessons: ["Parental love is full of protection and affection", "The devotee serves as the Lord's parent"] },
    "44": { title: "Devotional Service in Conjugal Love", summary: "The conjugal relationship with Kṛṣṇa and the mood of mādhurya-rasa are discussed.", keyLessons: ["Conjugal love is the highest expression of devotion", "The gopīs are the topmost devotees"] },
    "45": { title: "Laughing Ecstasy", summary: "The ecstatic symptoms of laughing and joy in the presence of Kṛṣṇa are described.", keyLessons: ["Ecstasy manifests as laughing in love", "The devotee experiences the Lord's humor"] },
    "46": { title: "Astonishment and Chivalry", summary: "The ecstatic emotions of astonishment and chivalry in devotional service.", keyLessons: ["Astonishment reveals the Lord's wonderful nature", "Chivalry displays the Lord's heroic qualities"] },
    "47": { title: "Compassion and Anger", summary: "The ecstatic emotions of compassion and anger in the advanced devotee.", keyLessons: ["Compassion and anger are transformed by love for Kṛṣṇa", "The devotee's emotions are transcendental"] },
    "48": { title: "Dread and Ghastliness", summary: "The ecstatic emotions of dread and ghastliness in the advanced devotee.", keyLessons: ["Dread and ghastliness become expressions of love", "The devotee experiences the Lord's power"] },
    "49": { title: "Mixing of Rasas", summary: "The mixing of different rasas and the combinations of devotional mellows.", keyLessons: ["The rasas can be combined in various ways", "The combinations of love are infinite"] },
    "50": { title: "Further Analysis of Mixed Rasas", summary: "Further analysis of the mixed rasas and their interactions.", keyLessons: ["The interactions of rasas are subtle and wonderful", "The advanced devotee relishes all combinations of love"] },
    "51": { title: "Perverted Expression of Mellows", summary: "The perverted expression of mellows in the material world and their distinction from spiritual rasa.", keyLessons: ["Material emotions are perverted reflections of spiritual rasa", "True rasa is found only in relationship with Kṛṣṇa"] },
  },

  "nectar of instruction": {
    "1": { title: "Text One", summary: "The spiritual master, the disciple, and the Vaiṣṇava are all to be offered respects; the contamination of the material world is to be renounced.", keyLessons: ["Offer respects to the guru, Vaiṣṇavas, and the Lord", "Renounce material identification"] },
    "2": { title: "Text Two", summary: "One should accept the spiritual master and serve him with great faith; through this service one can understand the Absolute Truth.", keyLessons: ["Accept a bona fide spiritual master", "Serve the guru with faith and surrender"] },
    "3": { title: "Text Three", summary: "By the association of the pure devotees, all doubts are dispelled and one becomes fixed in devotional service.", keyLessons: ["Association of devotees dispels doubts", "Hearing and chanting purify the heart"] },
    "4": { title: "Text Four", summary: "The cultivation of the creeper of devotion requires watering it with hearing and chanting, and protecting it from offenses.", keyLessons: ["The seed of devotion is watered by hearing and chanting", "Avoid offenses to the holy name"] },
    "5": { title: "Text Five", summary: "The devotee should be tolerant and forgiving, while the nondevotee should be avoided as a venomous snake.", keyLessons: ["Be tolerant like a tree", "Avoid the association of nondevotees"] },
    "6": { title: "Text Six", summary: "Excessive eating and sleeping are detrimental to devotional service; the devotee should be moderate.", keyLessons: ["Eat and sleep moderately", "Use the body for Kṛṣṇa's service"] },
    "7": { title: "Text Seven", summary: "The devotee should not be attached to material possessions, family, or home; he should be fully engaged in the Lord's service.", keyLessons: ["Detach from material possessions", "Engage everything in Kṛṣṇa's service"] },
    "8": { title: "Text Eight", summary: "One should live in a holy place and associate with the devotees of the Lord; solitude should be used for spiritual practice.", keyLessons: ["Live in a holy place", "Associate with devotees and practice bhakti"] },
    "9": { title: "Text Nine", summary: "The devotee should be eager to hear about the Lord's qualities and pastimes; this eagerness is the sign of advancement.", keyLessons: ["Develop eagerness to hear about Kṛṣṇa", "Hearing is the cornerstone of devotion"] },
    "10": { title: "Text Ten", summary: "The holy name is the most powerful means of spiritual realization; one should chant constantly without offense.", keyLessons: ["Chant the holy name constantly", "The holy name is the highest form of realization"] },
    "11": { title: "Text Eleven", summary: "The conclusion of all instruction is to engage the tongue, mind, and body in the loving service of the Lord.", keyLessons: ["Engage all faculties in Kṛṣṇa's service", "The perfection of life is pure devotion"] },
  },
};

export function findChapterOverview(book: string, chapter: number): ChapterOverview | null {
  const lower = book.toLowerCase();
  for (const [key, chapters] of Object.entries(chapterOverviews)) {
    if (lower.includes(key)) {
      return chapters[String(chapter)] || null;
    }
  }
  return null;
}
