import { VaisnavaEvent } from "./data";

export const fastLabels: Record<NonNullable<VaisnavaEvent["fastType"]>, string> = {
  none: "No fast",
  "till-sunrise": "Fast till next sunrise",
  "till-noon": "Fast till noon",
  "till-sunset": "Fast till sunset",
  "till-dusk": "Fast till dusk",
  "till-midnight": "Fast till midnight",
  "till-moonrise": "Fast till moonrise",
  nirjala: "Nirjala (no water)",
};

export const fastDetails: Record<NonNullable<VaisnavaEvent["fastType"]>, string> = {
  none: "No fasting restrictions on this day. Still, devotees are encouraged to take prasadam (sanctified food) and focus on hearing and chanting.",
  "till-sunrise": "On this day, devotees avoid grains, beans, pulses, and most vegetables from the previous day's sunset until the next sunrise. Drink water, milk, and fruit juices. Break fast after sunrise with grains only once the fasting time is complete.",
  "till-noon": "Avoid grains, beans, and pulses from sunrise until noon. Take water, milk, fruit, and other approved foods. Break fast with grains after noon.",
  "till-sunset": "Fast from grains, beans, and pulses from sunrise until sunset. This is a longer fast, so drink plenty of water and stay absorbed in hearing and chanting the Lord's glories.",
  "till-dusk": "Avoid grains, beans, and pulses from sunrise until dusk. Break fast after dusk with Krishna-prasadam.",
  "till-midnight": "A full-day fast from grains, beans, and pulses until midnight. This is observed for Krishna Janmashtami. Keep the day festive with kirtan, reading, and remembering the Lord's birth.",
  "till-moonrise": "Fast from grains, beans, and pulses until moonrise. The fast is broken once the moon is visible. Stay awake and chant Hare Krishna.",
  nirjala: "The strictest fast: no water, food, or drink at all. This is for advanced devotees with physical ability. Others may take water if needed. The most important aspect is increased remembrance of the Lord.",
};

export const vaisnavaEvents: VaisnavaEvent[] = ([
  // 2026 Ekadashis
  {
    id: "ek-2026-01-14",
    date: "2026-01-14",
    name: "Shat-tila Ekadashi",
    type: "ekadashi",
    description: "Shat-tila Ekadashi is observed by offering sesame seeds (til) in charity and worshipping Lord Krishna. It destroys the reactions of past sins.",
    fastType: "till-sunrise",
    breakFastStart: "15 Jan 2026, 07:35am (Kansas City, LT)",
    breakFastEnd: "15 Jan 2026, 08:48am (Kansas City, LT)",
  },
  {
    id: "ek-2026-01-28",
    date: "2026-01-28",
    name: "Bhaimi Ekadashi",
    type: "ekadashi",
    description: "Also known as Jaya Ekadashi, this day grants victory (jaya) to the soul and liberates from the reactions of material enjoyment.",
    fastType: "till-sunrise",
    breakFastStart: "29 Jan 2026, 07:45am (Kansas City, LT)",
    breakFastEnd: "29 Jan 2026, 10:50am (Kansas City, LT)",
  },
  {
    id: "ek-2026-02-12",
    date: "2026-02-12",
    name: "Vijaya Ekadashi",
    type: "ekadashi",
    description: "Vijaya Ekadashi gives victory in spiritual life and removes obstacles. It is described in the Puranas as a very auspicious day.",
    fastType: "till-sunrise",
    breakFastStart: "13 Feb 2026, 09:22am (Kansas City, LT)",
    breakFastEnd: "13 Feb 2026, 10:45am (Kansas City, LT)",
  },
  {
    id: "ek-2026-02-27",
    date: "2026-02-27",
    name: "Amalaki Ekadashi",
    type: "ekadashi",
    description: "Amalaki Ekadashi is observed by worshipping the amalaki (amla) tree, a form of Lord Vishnu. It bestows health and spiritual strength.",
    fastType: "till-sunrise",
    breakFastStart: "28 Feb 2026, 06:52am (Kansas City, LT)",
    breakFastEnd: "28 Feb 2026, 09:15am (Kansas City, LT)",
  },
  {
    id: "ek-2026-03-14",
    date: "2026-03-14",
    name: "Papamocani Ekadashi",
    type: "ekadashi",
    description: "Papamocani Ekadashi frees one from the reactions of sinful activities and is especially powerful for spiritual purification.",
    fastType: "till-sunrise",
    breakFastStart: "15 Mar 2026, 07:29am (Kansas City, DST)",
    breakFastEnd: "15 Mar 2026, 11:28am (Kansas City, DST)",
  },
  {
    id: "ek-2026-03-28",
    date: "2026-03-28",
    name: "Kamada Ekadashi",
    type: "ekadashi",
    description: "Kamada Ekadashi fulfills desires and removes curses. It is the first Ekadashi after Gaura Purnima and begins the new year.",
    fastType: "till-sunrise",
    breakFastStart: "29 Mar 2026, 07:07am (Kansas City, DST)",
    breakFastEnd: "29 Mar 2026, 11:18am (Kansas City, DST)",
  },
  {
    id: "ek-2026-04-13",
    date: "2026-04-13",
    name: "Varuthini Ekadashi",
    type: "ekadashi",
    description: "Varuthini Ekadashi protects one from all calamities and bestows the determination to follow the path of devotion.",
    fastType: "till-sunrise",
    breakFastStart: "14 Apr 2026, 06:42am (Kansas City, DST)",
    breakFastEnd: "14 Apr 2026, 11:06am (Kansas City, DST)",
  },
  {
    id: "ek-2026-04-27",
    date: "2026-04-27",
    name: "Mohini Ekadashi",
    type: "ekadashi",
    description: "Mohini Ekadashi commemorates the Lord's pastime as Mohini, who distributed nectar to the demigods. It grants relief from suffering.",
    fastType: "till-sunrise",
    breakFastStart: "28 Apr 2026, 06:23am (Kansas City, DST)",
    breakFastEnd: "28 Apr 2026, 08:24am (Kansas City, DST)",
  },
  {
    id: "ek-2026-05-12",
    date: "2026-05-12",
    name: "Apara Ekadashi",
    type: "ekadashi",
    description: "Apara Ekadashi is said to give unlimited spiritual benefit and destroys the reactions of all kinds of sins.",
    fastType: "till-sunrise",
    breakFastStart: "13 May 2026, 08:30am (Kansas City, DST)",
    breakFastEnd: "13 May 2026, 10:52am (Kansas City, DST)",
  },
  {
    id: "ek-2026-05-26",
    date: "2026-05-26",
    name: "Padmini Ekadashi",
    type: "ekadashi",
    description: "Padmini Ekadashi is observed during the extra month (Adhika-masa) and is very rare. It grants liberation and devotion.",
    fastType: "till-sunrise",
    breakFastStart: "27 May 2026, 05:56am (Kansas City, DST)",
    breakFastEnd: "27 May 2026, 10:49am (Kansas City, DST)",
  },
  {
    id: "ek-2026-06-11",
    date: "2026-06-11",
    name: "Parama Ekadashi",
    type: "ekadashi",
    description: "Parama Ekadashi is observed during the extra month (Adhika-masa) and is the best of all Ekadashis. It grants the supreme destination.",
    fastType: "till-sunrise",
    breakFastStart: "12 Jun 2026, 05:51am (Kansas City, DST)",
    breakFastEnd: "12 Jun 2026, 09:08am (Kansas City, DST)",
  },
  {
    id: "ek-2026-06-25",
    date: "2026-06-25",
    name: "Pandava Nirjala Ekadashi",
    type: "ekadashi",
    description: "Pandava Nirjala Ekadashi is a total fast (without water) and is the most austere. It removes the reactions of all sinful activities and bestows the benefit of all other Ekadashis.",
    fastType: "nirjala",
    breakFastStart: "26 Jun 2026, 05:54am (Kansas City, DST)",
    breakFastEnd: "26 Jun 2026, 10:52am (Kansas City, DST)",
  },
  {
    id: "ek-2026-07-10",
    date: "2026-07-10",
    name: "Yogini Ekadashi",
    type: "ekadashi",
    description: "Yogini Ekadashi frees one from the reactions of the most heinous sins and is especially powerful for spiritual purification.",
    fastType: "till-sunrise",
    breakFastStart: "11 Jul 2026, 06:01am (Kansas City, DST)",
    breakFastEnd: "11 Jul 2026, 10:56am (Kansas City, DST)",
  },
  {
    id: "ek-2026-07-24",
    date: "2026-07-24",
    name: "Devshayani Ekadashi",
    type: "ekadashi",
    description: "Also called Sayana Ekadashi, this marks the beginning of Lord Vishnu's four-month rest. It begins the Chaturmasya period.",
    fastType: "till-sunrise",
    breakFastStart: "25 Jul 2026, 07:41am (Kansas City, DST)",
    breakFastEnd: "25 Jul 2026, 11:00am (Kansas City, DST)",
  },
  {
    id: "ek-2026-08-08",
    date: "2026-08-08",
    name: "Kamika Ekadashi",
    type: "ekadashi",
    description: "Kamika Ekadashi destroys the reactions of all sins and fulfills the desires of the devotees. It occurs during the month of Shravana.",
    fastType: "till-sunrise",
    breakFastStart: "9 Aug 2026, 06:26am (Kansas City, DST)",
    breakFastEnd: "9 Aug 2026, 11:04am (Kansas City, DST)",
  },
  {
    id: "ek-2026-08-23",
    date: "2026-08-23",
    name: "Pavitraropana Ekadashi",
    type: "ekadashi",
    description: "Pavitraropana Ekadashi is observed by offering pavitra (sacred threads) to the Lord. It purifies one from all sinful reactions.",
    fastType: "till-sunrise",
    breakFastStart: "24 Aug 2026, 06:39am (Kansas City, DST)",
    breakFastEnd: "24 Aug 2026, 11:06am (Kansas City, DST)",
  },
  {
    id: "ek-2026-09-07",
    date: "2026-09-07",
    name: "Annada Ekadashi",
    type: "ekadashi",
    description: "Annada Ekadashi is observed by giving food to others. It bestows the results of all pious activities and removes the fear of death.",
    fastType: "till-sunrise",
    breakFastStart: "8 Sep 2026, 06:53am (Kansas City, DST)",
    breakFastEnd: "8 Sep 2026, 11:08am (Kansas City, DST)",
  },
  {
    id: "ek-2026-09-22",
    date: "2026-09-22",
    name: "Parsva Ekadashi",
    type: "ekadashi",
    description: "Parsva Ekadashi occurs during the time Lord Vishnu turns on His side. It is an important Ekadashi for spiritual advancement.",
    fastType: "till-sunrise",
    breakFastStart: "23 Sep 2026, 07:06am (Kansas City, DST)",
    breakFastEnd: "23 Sep 2026, 11:09am (Kansas City, DST)",
  },
  {
    id: "ek-2026-10-06",
    date: "2026-10-06",
    name: "Indira Ekadashi",
    type: "ekadashi",
    description: "Indira Ekadashi is especially for the liberation of ancestors and removes all sinful reactions. It is observed with great care.",
    fastType: "till-sunrise",
    breakFastStart: "7 Oct 2026, 07:20am (Kansas City, DST)",
    breakFastEnd: "7 Oct 2026, 11:10am (Kansas City, DST)",
  },
  {
    id: "ek-2026-10-21",
    date: "2026-10-21",
    name: "Pasankusa Ekadashi",
    type: "ekadashi",
    description: "Pasankusa Ekadashi destroys the reactions of all sinful activities and bestows the result of performing great sacrifices.",
    fastType: "till-sunrise",
    breakFastStart: "22 Oct 2026, 10:16am (Kansas City, DST)",
    breakFastEnd: "22 Oct 2026, 11:13am (Kansas City, DST)",
  },
  {
    id: "ek-2026-11-04",
    date: "2026-11-04",
    name: "Rama Ekadashi",
    type: "ekadashi",
    description: "Rama Ekadashi removes the greatest sins and is a very powerful day for worshipping Lord Vishnu and His consort Lakshmi.",
    fastType: "till-sunrise",
    breakFastStart: "5 Nov 2026, 06:50am (Kansas City, LT)",
    breakFastEnd: "5 Nov 2026, 10:17am (Kansas City, LT)",
  },
  {
    id: "ek-2026-11-20",
    date: "2026-11-20",
    name: "Devutthana Ekadashi",
    type: "ekadashi",
    description: "Devutthana Ekadashi marks the time when Lord Vishnu wakes up from His four-month rest. The marriage season begins after this day.",
    fastType: "till-noon",
    breakFastStart: "21 Nov 2026, 07:08am (Kansas City, LT)",
    breakFastEnd: "21 Nov 2026, 10:25am (Kansas City, LT)",
  },
  {
    id: "ek-2026-12-04",
    date: "2026-12-04",
    name: "Utpanna Ekadashi",
    type: "ekadashi",
    description: "Utpanna Ekadashi is the day when the Ekadashi tithi first appeared. It grants the result of all pious activities and destroys sins.",
    fastType: "till-sunrise",
    breakFastStart: "5 Dec 2026, 07:22am (Kansas City, LT)",
    breakFastEnd: "5 Dec 2026, 10:33am (Kansas City, LT)",
  },
  {
    id: "ek-2026-12-20",
    date: "2026-12-20",
    name: "Mokshada Ekadashi / Vaikuntha Ekadashi",
    type: "ekadashi",
    description: "Mokshada Ekadashi is also celebrated as Vaikuntha Ekadashi. It grants liberation and the doors of the spiritual world are opened.",
    fastType: "till-sunrise",
    breakFastStart: "21 Dec 2026, 07:33am (Kansas City, LT)",
    breakFastEnd: "21 Dec 2026, 10:42am (Kansas City, LT)",
  },

  // 2027 Ekadashis
  {
    id: "ek-2027-01-02",
    date: "2027-01-02",
    name: "Saphala Ekadashi",
    type: "ekadashi",
    description: "Saphala Ekadashi fulfills all desires and makes every endeavor successful. It is observed at the beginning of the year.",
    fastType: "till-sunrise",
    breakFastStart: "3 Jan 2027, after 11:12am (Kansas City, LT)",
  },
  {
    id: "ek-2027-01-18",
    date: "2027-01-18",
    name: "Pausha Putrada Ekadashi",
    type: "ekadashi",
    description: "Pausha Putrada Ekadashi bestows good children and fulfills the desires of devotees. It is especially beneficial for families.",
    fastType: "till-sunrise",
    breakFastStart: "19 Jan 2027, 07:34am (Kansas City, LT)",
    breakFastEnd: "19 Jan 2027, 10:50am (Kansas City, LT)",
  },
  {
    id: "ek-2027-02-01",
    date: "2027-02-01",
    name: "Shat-tila Ekadashi",
    type: "ekadashi",
    description: "Shat-tila Ekadashi is observed by offering sesame seeds in charity and worshipping the Lord. It destroys reactions of sins.",
    fastType: "till-sunrise",
    breakFastStart: "2 Feb 2027, 07:24am (Kansas City, LT)",
    breakFastEnd: "2 Feb 2027, 10:49am (Kansas City, LT)",
  },
  {
    id: "ek-2027-02-17",
    date: "2027-02-17",
    name: "Bhaimi Ekadashi",
    type: "ekadashi",
    description: "Also known as Jaya Ekadashi, this day grants victory (jaya) to the soul and liberates from the reactions of material enjoyment.",
    fastType: "till-sunrise",
    breakFastStart: "18 Feb 2027, 07:06am (Kansas City, LT)",
    breakFastEnd: "18 Feb 2027, 10:43am (Kansas City, LT)",
  },
  {
    id: "ek-2027-03-03",
    date: "2027-03-03",
    name: "Vijaya Ekadashi",
    type: "ekadashi",
    description: "Vijaya Ekadashi gives victory and removes obstacles in spiritual life. It is observed before Gaura Purnima.",
    fastType: "till-sunrise",
    breakFastStart: "4 Mar 2027, 06:46am (Kansas City, LT)",
    breakFastEnd: "4 Mar 2027, 10:35am (Kansas City, LT)",
  },
  {
    id: "ek-2027-03-18",
    date: "2027-03-18",
    name: "Amalaki Ekadashi",
    type: "ekadashi",
    description: "Amalaki Ekadashi is observed by worshipping the amalaki tree, a form of the Lord. It bestows health and devotion.",
    fastType: "till-sunrise",
    breakFastStart: "19 Mar 2027, 07:23am (Kansas City, DST)",
    breakFastEnd: "19 Mar 2027, 11:25am (Kansas City, DST)",
  },
  {
    id: "ek-2027-04-02",
    date: "2027-04-02",
    name: "Papamocani Ekadashi",
    type: "ekadashi",
    description: "Papamocani Ekadashi frees one from the reactions of sinful activities and is especially powerful for spiritual purification.",
    fastType: "till-sunrise",
    breakFastStart: "3 Apr 2027, 06:59am (Kansas City, DST)",
    breakFastEnd: "3 Apr 2027, 11:14am (Kansas City, DST)",
  },
  {
    id: "ek-2027-04-16",
    date: "2027-04-16",
    name: "Kamada Ekadashi",
    type: "ekadashi",
    description: "Kamada Ekadashi fulfills desires and is the first Ekadashi after Gaura Purnima.",
    fastType: "till-sunrise",
    breakFastStart: "17 Apr 2027, 06:38am (Kansas City, DST)",
    breakFastEnd: "17 Apr 2027, 11:05am (Kansas City, DST)",
  },
  {
    id: "ek-2027-05-02",
    date: "2027-05-02",
    name: "Varuthini Ekadashi",
    type: "ekadashi",
    description: "Varuthini Ekadashi protects from calamities and strengthens determination in devotion.",
    fastType: "till-sunrise",
    breakFastStart: "3 May 2027, 06:17am (Kansas City, DST)",
    breakFastEnd: "3 May 2027, 09:36am (Kansas City, DST)",
  },
  {
    id: "ek-2027-05-16",
    date: "2027-05-16",
    name: "Mohini Ekadashi",
    type: "ekadashi",
    description: "Mohini Ekadashi commemorates the Lord's pastime as Mohini. It grants relief from suffering.",
    fastType: "till-sunrise",
    breakFastStart: "17 May 2027, 06:03am (Kansas City, DST)",
    breakFastEnd: "17 May 2027, 10:51am (Kansas City, DST)",
  },
  {
    id: "ek-2027-05-31",
    date: "2027-05-31",
    name: "Apara Ekadashi",
    type: "ekadashi",
    description: "Apara Ekadashi gives unlimited spiritual benefit and destroys the reactions of all sins.",
    fastType: "till-sunrise",
    breakFastStart: "1 Jun 2027, 05:54am (Kansas City, DST)",
    breakFastEnd: "1 Jun 2027, 10:49am (Kansas City, DST)",
  },
  {
    id: "ek-2027-06-14",
    date: "2027-06-14",
    name: "Nirjala Ekadashi",
    type: "ekadashi",
    description: "Nirjala Ekadashi is a total fast without water. It removes all sinful reactions and bestows the benefit of all Ekadashis.",
    fastType: "nirjala",
    breakFastStart: "15 Jun 2027, 05:51am (Kansas City, DST)",
    breakFastEnd: "15 Jun 2027, 10:49am (Kansas City, DST)",
  },
  {
    id: "ek-2027-06-30",
    date: "2027-06-30",
    name: "Yogini Ekadashi",
    type: "ekadashi",
    description: "Yogini Ekadashi frees one from the reactions of the most heinous sins.",
    fastType: "till-sunrise",
    breakFastStart: "1 Jul 2027, 05:56am (Kansas City, DST)",
    breakFastEnd: "1 Jul 2027, 07:46am (Kansas City, DST)",
  },
  {
    id: "ek-2027-07-13",
    date: "2027-07-13",
    name: "Devshayani Ekadashi",
    type: "ekadashi",
    description: "Devshayani Ekadashi begins the four-month rest of Lord Vishnu and Chaturmasya.",
    fastType: "till-sunrise",
    breakFastStart: "14 Jul 2027, 09:04am (Kansas City, DST)",
    breakFastEnd: "14 Jul 2027, 10:57am (Kansas City, DST)",
  },
  {
    id: "ek-2027-07-29",
    date: "2027-07-29",
    name: "Kamika Ekadashi",
    type: "ekadashi",
    description: "Kamika Ekadashi destroys all sins and fulfills the desires of devotees.",
    fastType: "till-sunrise",
    breakFastStart: "30 Jul 2027, 06:16am (Kansas City, DST)",
    breakFastEnd: "30 Jul 2027, 11:01am (Kansas City, DST)",
  },
  {
    id: "ek-2027-08-12",
    date: "2027-08-12",
    name: "Pavitraropana Ekadashi",
    type: "ekadashi",
    description: "Pavitraropana Ekadashi is observed by offering pavitra (sacred threads) to the Lord. It purifies one from all sinful reactions.",
    fastType: "till-sunrise",
    breakFastStart: "13 Aug 2027, 06:29am (Kansas City, DST)",
    breakFastEnd: "13 Aug 2027, 11:05am (Kansas City, DST)",
  },
  {
    id: "ek-2027-08-27",
    date: "2027-08-27",
    name: "Annada Ekadashi",
    type: "ekadashi",
    description: "Annada Ekadashi is observed by giving food to others. It bestows the results of all pious activities and removes the fear of death.",
    fastType: "till-sunrise",
    breakFastStart: "28 Aug 2027, 07:27am (Kansas City, DST)",
    breakFastEnd: "28 Aug 2027, 11:07am (Kansas City, DST)",
  },
  {
    id: "ek-2027-09-11",
    date: "2027-09-11",
    name: "Parsva Ekadashi",
    type: "ekadashi",
    description: "Parsva Ekadashi occurs when Lord Vishnu turns on His side during His rest.",
    fastType: "till-sunrise",
    breakFastStart: "12 Sep 2027, 06:56am (Kansas City, DST)",
    breakFastEnd: "12 Sep 2027, 11:08am (Kansas City, DST)",
  },
  {
    id: "ek-2027-09-26",
    date: "2027-09-26",
    name: "Indira Ekadashi",
    type: "ekadashi",
    description: "Indira Ekadashi is for the liberation of ancestors and removes all sinful reactions.",
    fastType: "till-sunrise",
    breakFastStart: "27 Sep 2027, 07:10am (Kansas City, DST)",
    breakFastEnd: "27 Sep 2027, 11:09am (Kansas City, DST)",
  },
  {
    id: "ek-2027-10-10",
    date: "2027-10-10",
    name: "Pasankusa Ekadashi",
    type: "ekadashi",
    description: "Pasankusa Ekadashi destroys the reactions of all sinful activities and bestows the results of great sacrifices.",
    fastType: "till-sunrise",
    breakFastStart: "11 Oct 2027, 10:11am (Kansas City, DST)",
    breakFastEnd: "11 Oct 2027, 11:11am (Kansas City, DST)",
  },
  {
    id: "ek-2027-10-25",
    date: "2027-10-25",
    name: "Rama Ekadashi",
    type: "ekadashi",
    description: "Rama Ekadashi removes the greatest sins and is powerful for worshipping Lord Vishnu and Lakshmi.",
    fastType: "till-sunrise",
    breakFastStart: "26 Oct 2027, 07:39am (Kansas City, DST)",
    breakFastEnd: "26 Oct 2027, 11:14am (Kansas City, DST)",
  },
  {
    id: "ek-2027-11-09",
    date: "2027-11-09",
    name: "Devutthana Ekadashi",
    type: "ekadashi",
    description: "Devutthana Ekadashi marks when Lord Vishnu wakes from His four-month rest.",
    fastType: "till-noon",
    breakFastStart: "10 Nov 2027, 06:55am (Kansas City, LT)",
    breakFastEnd: "10 Nov 2027, 10:19am (Kansas City, LT)",
  },
  {
    id: "ek-2027-11-23",
    date: "2027-11-23",
    name: "Utpanna Ekadashi",
    type: "ekadashi",
    description: "Utpanna Ekadashi is the day the Ekadashi tithi first appeared.",
    fastType: "till-sunrise",
    breakFastStart: "24 Nov 2027, 07:11am (Kansas City, LT)",
    breakFastEnd: "24 Nov 2027, 10:26am (Kansas City, LT)",
  },
  {
    id: "ek-2027-12-09",
    date: "2027-12-09",
    name: "Mokshada Ekadashi",
    type: "ekadashi",
    description: "Mokshada Ekadashi grants liberation and the benefit of the Bhagavad-gita.",
    fastType: "till-sunrise",
    breakFastStart: "10 Dec 2027, 07:26am (Kansas City, LT)",
    breakFastEnd: "10 Dec 2027, 10:36am (Kansas City, LT)",
  },
  {
    id: "ek-2027-12-23",
    date: "2027-12-23",
    name: "Saphala Ekadashi",
    type: "ekadashi",
    description: "Saphala Ekadashi fulfills desires and makes endeavors successful.",
    fastType: "till-sunrise",
    breakFastStart: "24 Dec 2027, 07:35am (Kansas City, LT)",
    breakFastEnd: "24 Dec 2027, 10:43am (Kansas City, LT)",
  },

  // 2026 Festivals & Appearance/Disappearance
  {
    id: "fest-2026-01-31",
    date: "2026-01-31",
    name: "Nityananda Trayodashi",
    type: "appearance",
    description: "Sri Nityananda Prabhu is the original spiritual master and the most intimate associate of Sri Chaitanya Mahaprabhu. He is an expansion of Lord Balarama and first appeared in this world to give the mercy of love of God to everyone, regardless of qualification. On this day, devotees fast until noon, read about Nityananda Prabhu's pastimes, and pray for the humility to receive the gift of Krishna-bhakti.",
    personDeity: "Sri Nityananda Prabhu",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-02-23",
    date: "2026-02-23",
    name: "Sri Madhvacharya — Disappearance",
    type: "disappearance",
    description: "Sri Madhvacharya is the great Vaishnava philosopher and founder of the Dvaita (dualist) school. He appeared in the 13th century to strongly establish devotion to Lord Vishnu and the eternal distinction between the individual soul and the Supreme Lord. His disappearance day is a time to honor the acharyas who guard the path of bhakti.",
    personDeity: "Sri Madhvacharya",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-03-03",
    date: "2026-03-03",
    name: "Gaura Purnima",
    type: "appearance",
    description: "Gaura Purnima celebrates the appearance of Sri Chaitanya Mahaprabhu, the golden avatara and combined form of Sri Krishna and Srimati Radharani. He appeared in Bengal in 1486 to teach the path of sankirtana, chanting the holy names, and to freely distribute love of God to everyone. It is the most important festival for Gaudiya Vaishnavas.",
    personDeity: "Sri Chaitanya Mahaprabhu",
    fastType: "till-moonrise",
  },
  {
    id: "fest-2026-03-11",
    date: "2026-03-11",
    name: "Sri Srivasa Pandita — Appearance",
    type: "appearance",
    description: "Sri Srivasa Pandita was a close associate of Sri Chaitanya Mahaprabhu and a member of the Pancha Tattva. He opened his home in Navadvipa for the Lord's nightly sankirtana gatherings, making it the birthplace of the congregational chanting movement. On his appearance day, devotees remember the joy of sharing Krishna-katha in the association of devotees.",
    personDeity: "Sri Srivasa Pandita",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-03-16",
    date: "2026-03-16",
    name: "Sri Govinda Ghosh — Disappearance",
    type: "disappearance",
    description: "Sri Govinda Ghosh was a renowned devotee and kirtana singer in the sankirtana movement of Sri Chaitanya Mahaprabhu. His heartfelt singing expressed deep love for Krishna and inspired all who heard it. His disappearance day is honored by remembering the potency of devotional music and the mercy of the Lord's associates.",
    personDeity: "Sri Govinda Ghosh",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-03-23",
    date: "2026-03-23",
    name: "Sri Ramanujacarya — Appearance",
    type: "appearance",
    description: "Sri Ramanujacarya (1017–1137) was a great teacher who spread the philosophy of devotion, or bhakti, and established the Sri Vaishnava tradition. He emphasized that the soul is eternally a servant of the Supreme Lord Vishnu and that pure devotion is the path to liberation. His appearance day is a time to honor the teachers who have preserved the path of bhakti for us.",
    personDeity: "Sri Ramanujacarya",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-03-27",
    date: "2026-03-27",
    name: "Rama Navami",
    type: "appearance",
    description: "Rama Navami celebrates the appearance of Lord Sri Ramacandra, the ideal king and the seventh incarnation of Lord Vishnu. He descended to re-establish dharma and to show the world the perfect example of duty, righteousness, and compassion. Devotees fast until sunset, chant the Hare Krishna maha-mantra, and read the Ramayana.",
    personDeity: "Lord Sri Ramacandra",
    fastType: "till-sunset",
  },
  {
    id: "fest-2026-04-30",
    date: "2026-04-30",
    name: "Nrsimha Chaturdashi",
    type: "appearance",
    description: "Nrsimha Chaturdashi celebrates the appearance of Lord Nrsimhadeva, the half-man, half-lion incarnation of the Lord. He appeared to protect His young devotee Prahlada Maharaja and to destroy the demon Hiranyakasipu, showing that pure devotion is always protected by the Lord. Devotees fast until dusk and remember the Lord's power and mercy.",
    personDeity: "Lord Nrsimhadeva",
    fastType: "till-dusk",
  },
  {
    id: "fest-2026-07-16",
    date: "2026-07-16",
    name: "Ratha Yatra",
    type: "festival",
    description: "Ratha Yatra is the famous annual chariot festival of Lord Jagannatha, His brother Baladeva, and His sister Subhadra. The Deities ride on grand carts through the streets so that everyone can see and serve Them. It reminds us that the Lord comes out to meet His devotees, and it began in Jagannatha Puri thousands of years ago.",
    personDeity: "Lord Jagannatha",
    fastType: "none",
  },
  {
    id: "fest-2026-08-28",
    date: "2026-08-28",
    name: "Balarama Jayanti",
    type: "appearance",
    description: "Balarama Jayanti celebrates the appearance of Lord Balarama, the original spiritual master and the elder brother of Lord Krishna. He is an expansion of Lord Vishnu and appeared to assist Krishna in His pastimes. As the original guru, Balarama teaches us the importance of serving the Lord with all our strength. This day also marks the end of Jhulana Yatra, the swing festival.",
    personDeity: "Lord Balarama",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-09-04",
    date: "2026-09-04",
    name: "Sri Krishna Janmashtami",
    type: "appearance",
    description: "Sri Krishna Janmashtami is the appearance day of Lord Sri Krishna, the Supreme Personality of Godhead. Krishna appeared in Mathura over five thousand years ago to protect the devotees, destroy the wicked, and re-establish the principles of religion. It is the most widely celebrated Vaishnava festival. Devotees fast until midnight, hear and chant Krishna's pastimes, and welcome the Lord at the time of His birth.",
    personDeity: "Lord Sri Krishna",
    fastType: "till-midnight",
  },
  {
    id: "fest-2026-09-05",
    date: "2026-09-05",
    name: "Nandotsava & Vyasa Puja",
    type: "appearance",
    description: "Nandotsava is the joyful festival celebrating Krishna's birth and the gifts given by Nanda Maharaja to everyone. On the same day, Gaudiya Vaishnavas observe Vyasa Puja, the appearance day of Srila Prabhupada, the founder-acharya of ISKCON. Srila Prabhupada spread Krishna consciousness worldwide and is honored as the spiritual father who gave the treasure of bhakti to the whole world.",
    personDeity: "Srila Prabhupada",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-09-19",
    date: "2026-09-19",
    name: "Radhastami",
    type: "appearance",
    description: "Radhastami celebrates the appearance of Srimati Radharani, the consort of Lord Krishna and the personification of pure devotional love. She is the supreme goddess of fortune and the embodiment of selfless love for Krishna. Her appearance day is a chance for devotees to pray for the quality of devotion that pleases the Lord. Devotees fast until noon and meditate on the Lord's beautiful pastimes with Srimati Radharani.",
    personDeity: "Srimati Radharani",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-09-23",
    date: "2026-09-23",
    name: "Sri Vamana Dvadasi",
    type: "appearance",
    description: "Sri Vamana Dvadasi celebrates the appearance of Lord Vamanadeva, the dwarf-brahmana incarnation of the Lord. He appeared to reclaim the universe from the generous King Bali by asking for only three steps of land, then expanded to cover the entire cosmos. This pastime teaches that the Lord can accept any form and that true devotion is the most valuable offering. Devotees fast until noon and remember the Lord's wonderful mercy.",
    personDeity: "Lord Vamanadeva",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-09-24",
    date: "2026-09-24",
    name: "Srila Bhaktivinoda Thakura — Appearance",
    type: "appearance",
    description: "Srila Bhaktivinoda Thakura (1838–1914) was a great Vaishnava acharya, songwriter, and the father of the modern Gaudiya Vaishnava mission. He wrote many devotional books and songs that explain the teachings of Lord Chaitanya in a clear, accessible way. His appearance day is a time to honor the spiritual lineage and to study the foundational literature of the Krishna consciousness movement.",
    personDeity: "Srila Bhaktivinoda Thakura",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-10-14",
    date: "2026-10-14",
    name: "Srila Narottama Dasa Thakura — Disappearance",
    type: "disappearance",
    description: "Srila Narottama Dasa Thakura (1536–1606) was a great Vaishnava saint and composer of many devotional songs that are still sung by devotees today. He helped spread the sankirtana movement and taught the importance of humility, compassion, and pure devotion. His disappearance day is an opportunity to remember the lives of the great devotees and to pray for their mercy.",
    personDeity: "Srila Narottama Dasa Thakura",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-11-09",
    date: "2026-11-09",
    name: "Govardhan Puja / Annakuta",
    type: "festival",
    description: "Govardhan Puja, also called Annakuta, is the festival of offering gratitude to Govardhan Hill. The day after Diwali, devotees remember how Lord Krishna lifted Govardhan Hill on His little finger to protect the residents of Vrindavana from a devastating storm. A large offering of vegetarian food (annakuta) is prepared, and the festival reminds us that the Lord protects those who take shelter of Him. There is no fasting on this day.",
    personDeity: "Lord Sri Krishna",
    fastType: "none",
  },
  {
    id: "fest-2026-11-27",
    date: "2026-11-27",
    name: "Srila Bhaktisiddhanta Sarasvati Thakura — Disappearance",
    type: "disappearance",
    description: "Srila Bhaktisiddhanta Sarasvati Thakura (1874–1937) was the spiritual master of Srila Prabhupada and a powerful preacher of Gaudiya Vaishnavism. He founded the Gaudiya Math and sent many missionaries to spread the teachings of Lord Chaitanya throughout India. His disappearance day is a time to remember the tireless service of the acharyas who make Krishna consciousness available to the world.",
    personDeity: "Srila Bhaktisiddhanta Sarasvati Thakura",
    fastType: "till-noon",
  },
  {
    id: "fest-2026-12-20",
    date: "2026-12-20",
    name: "Gita Jayanti",
    type: "festival",
    description: "Gita Jayanti is the day when Lord Krishna spoke the Bhagavad-gita to His friend and devotee Arjuna on the battlefield of Kurukshetra. The Bhagavad-gita is one of the most important scriptures in the world, teaching the science of self-realization, devotion, and the soul's relationship with God. On this day, devotees read, chant, and distribute the Bhagavad-gita to others.",
    personDeity: "Lord Sri Krishna",
    fastType: "till-sunrise",
  },

  // 2027 Festivals & Appearance/Disappearance
  {
    id: "fest-2027-01-13",
    date: "2027-01-13",
    name: "Sri Advaita Acarya — Appearance",
    type: "appearance",
    description: "Sri Advaita Acarya was a principal associate of Sri Chaitanya Mahaprabhu and a member of the Pancha Tattva. He is known as the 'first of the Pancha Tattva' because he prayed for the Lord to descend into the world to deliver the fallen souls. His appearance day reminds us of the importance of calling out to the Lord and inviting His mercy into our lives.",
    personDeity: "Sri Advaita Acarya",
    fastType: "till-noon",
  },
  {
    id: "fest-2027-02-19",
    date: "2027-02-19",
    name: "Nityananda Trayodashi",
    type: "appearance",
    description: "Sri Nityananda Prabhu is the original spiritual master and the most intimate associate of Sri Chaitanya Mahaprabhu. He is an expansion of Lord Balarama and first appeared in this world to give the mercy of love of God to everyone, regardless of qualification. On this day, devotees fast until noon, read about Nityananda Prabhu's pastimes, and pray for the humility to receive the gift of Krishna-bhakti.",
    personDeity: "Sri Nityananda Prabhu",
    fastType: "till-noon",
  },
  {
    id: "fest-2027-02-25",
    date: "2027-02-25",
    name: "Srila Bhaktisiddhanta Sarasvati Thakura — Appearance",
    type: "appearance",
    description: "Srila Bhaktisiddhanta Sarasvati Thakura (1874–1937) was a great reformer, preacher, and the spiritual master of Srila Prabhupada. He founded the Gaudiya Math and organized extensive preaching to spread the teachings of Lord Chaitanya throughout India and beyond. His appearance day is a time to honor his tireless service and to pray for the strength to share Krishna consciousness with others.",
    personDeity: "Srila Bhaktisiddhanta Sarasvati Thakura",
    fastType: "till-noon",
  },
  {
    id: "fest-2027-03-04",
    date: "2027-03-04",
    name: "Gaura Purnima",
    type: "appearance",
    description: "Gaura Purnima celebrates the appearance of Sri Chaitanya Mahaprabhu, the golden avatara and combined form of Sri Krishna and Srimati Radharani. He appeared in Bengal in 1486 to teach the path of sankirtana, chanting the holy names, and to freely distribute love of God to everyone. It is the most important festival for Gaudiya Vaishnavas.",
    personDeity: "Sri Chaitanya Mahaprabhu",
    fastType: "till-moonrise",
  },
  {
    id: "fest-2027-04-16",
    date: "2027-04-16",
    name: "Rama Navami",
    type: "appearance",
    description: "Rama Navami celebrates the appearance of Lord Sri Ramacandra, the ideal king and the seventh incarnation of Lord Vishnu. He descended to re-establish dharma and to show the world the perfect example of duty, righteousness, and compassion. Devotees fast until sunset, chant the Hare Krishna maha-mantra, and read the Ramayana.",
    personDeity: "Lord Sri Ramacandra",
    fastType: "till-sunset",
  },
  {
    id: "fest-2027-04-30",
    date: "2027-04-30",
    name: "Nrsimha Chaturdashi",
    type: "appearance",
    description: "Nrsimha Chaturdashi celebrates the appearance of Lord Nrsimhadeva, the half-man, half-lion incarnation of the Lord. He appeared to protect His young devotee Prahlada Maharaja and to destroy the demon Hiranyakasipu, showing that pure devotion is always protected by the Lord. Devotees fast until dusk and remember the Lord's power and mercy.",
    personDeity: "Lord Nrsimhadeva",
    fastType: "till-dusk",
  },
  {
    id: "fest-2027-09-03",
    date: "2027-09-03",
    name: "Sri Krishna Janmashtami",
    type: "appearance",
    description: "Sri Krishna Janmashtami is the appearance day of Lord Sri Krishna, the Supreme Personality of Godhead. Krishna appeared in Mathura over five thousand years ago to protect the devotees, destroy the wicked, and re-establish the principles of religion. It is the most widely celebrated Vaishnava festival. Devotees fast until midnight, hear and chant Krishna's pastimes, and welcome the Lord at the time of His birth.",
    personDeity: "Lord Sri Krishna",
    fastType: "till-midnight",
  },
  {
    id: "fest-2027-09-04",
    date: "2027-09-04",
    name: "Nandotsava & Vyasa Puja",
    type: "appearance",
    description: "Nandotsava is the joyful festival celebrating Krishna's birth and the gifts given by Nanda Maharaja to everyone. On the same day, Gaudiya Vaishnavas observe Vyasa Puja, the appearance day of Srila Prabhupada, the founder-acharya of ISKCON. Srila Prabhupada spread Krishna consciousness worldwide and is honored as the spiritual father who gave the treasure of bhakti to the whole world.",
    personDeity: "Srila Prabhupada",
    fastType: "till-noon",
  },
  {
    id: "fest-2027-09-19",
    date: "2027-09-19",
    name: "Radhastami",
    type: "appearance",
    description: "Radhastami celebrates the appearance of Srimati Radharani, the consort of Lord Krishna and the personification of pure devotional love. She is the supreme goddess of fortune and the embodiment of selfless love for Krishna. Her appearance day is a chance for devotees to pray for the quality of devotion that pleases the Lord. Devotees fast until noon and meditate on the Lord's beautiful pastimes with Srimati Radharani.",
    personDeity: "Srimati Radharani",
    fastType: "till-noon",
  },
  // Kārtika (Dāmodara) month 2026: Oct 18 – Nov 15
  {
    id: "fest-2026-10-18",
    date: "2026-10-18",
    name: "Kārtika Begins (Dāmodara Month)",
    type: "festival",
    description: "Kārtika (Dāmodara month) begins today. This is one of the most sacred months for Vaiṣṇavas. Devotees often take a vow (vrata) to increase their daily rounds of japa, offer ghee lamps (dīpa-dāna) to Lord Dāmodara each evening, sing the Dāmodarāṣṭaka prayers, and intensify hearing and chanting. Many aim for 24, 32, or 64 rounds daily during this month. Extra service, charity, and worship performed in Kārtika yield magnified spiritual results.",
    personDeity: "Lord Dāmodara",
  },
  {
    id: "fest-2026-11-15",
    date: "2026-11-15",
    name: "Kārtika Ends (Dāmodara Month)",
    type: "festival",
    description: "The final day of Kārtika (Dāmodara month). Today is the last day to complete any Kārtika vratas. Devotees offer final dīpa-dāna, express gratitude for the month's mercy, and pray that the intensified practice carries forward. It is auspicious to continue any good habits cultivated during this month.",
    personDeity: "Lord Dāmodara",
  },
  // Kārtika (Dāmodara) month 2027: Oct 7 – Nov 5
  {
    id: "fest-2027-10-07",
    date: "2027-10-07",
    name: "Kārtika Begins (Dāmodara Month)",
    type: "festival",
    description: "Kārtika (Dāmodara month) begins today. This is one of the most sacred months for Vaiṣṇavas. Devotees often take a vow (vrata) to increase their daily rounds of japa, offer ghee lamps (dīpa-dāna) to Lord Dāmodara each evening, sing the Dāmodarāṣṭaka prayers, and intensify hearing and chanting. Many aim for 24, 32, or 64 rounds daily during this month. Extra service, charity, and worship performed in Kārtika yield magnified spiritual results.",
    personDeity: "Lord Dāmodara",
  },
  {
    id: "fest-2027-11-05",
    date: "2027-11-05",
    name: "Kārtika Ends (Dāmodara Month)",
    type: "festival",
    description: "The final day of Kārtika (Dāmodara month). Today is the last day to complete any Kārtika vratas. Devotees offer final dīpa-dāna, express gratitude for the month's mercy, and pray that the intensified practice carries forward. It is auspicious to continue any good habits cultivated during this month.",
    personDeity: "Lord Dāmodara",
  },
] as VaisnavaEvent[]).sort((a, b) => a.date.localeCompare(b.date));

// Kārtika (Dāmodara month) date ranges
const kartikaRanges: [string, string][] = [
  ["2026-10-18", "2026-11-15"],
  ["2027-10-07", "2027-11-05"],
];

export function isKartikaDate(date: string): boolean {
  return kartikaRanges.some(([start, end]) => date >= start && date <= end);
}

export function getVaisnavaEventsForDate(date: string): VaisnavaEvent[] {
  return vaisnavaEvents.filter((e) => e.date === date);
}

export function getUpcomingVaisnavaEvents(date: string, count = 5): VaisnavaEvent[] {
  return vaisnavaEvents.filter((e) => e.date >= date).slice(0, count);
}

export function getVaisnavaEventsInRange(start: string, end: string): VaisnavaEvent[] {
  return vaisnavaEvents.filter((e) => e.date >= start && e.date <= end);
}
